export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_ERROR = "POST_USER_ERROR";

export const SAVE_USER_KEY = "SAVE_USER_KEY";

export const DELETE_USER_DATA_REQUEST = "DELETE_USER_DATA";
export const DELETE_USER_DATA_RESPONSE = "DELETE_USER_DATA_RESPONSE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";


// *---*---* Albums *---*---*

export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_RESPONSE = 'GET_ALBUMS_RESPONSE';

export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_RESPONSE = 'CREATE_ALBUM_RESPONSE';

export const EDIT_ALBUM_REQUEST = 'EDIT_ALBUM_REQUEST';
export const EDIT_ALBUM_RESPONSE = 'EDIT_ALBUM_RESPONSE';

export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_RESPONSE = 'DELETE_ALBUM_RESPONSE';

export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM';

// *---*---* Photos *---*---*

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_RESPONSE = 'GET_PHOTOS_RESPONSE';

export const CREATE_PHOTO_REQUEST = 'CREATE_PHOTO_REQUEST';
export const CREATE_PHOTO_RESPONSE = 'CREATE_PHOTO_RESPONSE';

export const EDIT_PHOTO_REQUEST = 'EDIT_PHOTO_REQUEST';
export const EDIT_PHOTO_RESPONSE = 'EDIT_PHOTO_RESPONSE';

export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO_REQUEST';
export const DELETE_PHOTO_RESPONSE = 'DELETE_PHOTO_RESPONSE';

export const SET_CURRENT_PHOTO = 'SET_CURRENT_PHOTO';