export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_ERROR = "POST_USER_ERROR";

// *---*---* Albums *---*---*

export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_RESPONSE = 'GET_ALBUMS_RESPONSE';


export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_RESPONSE = 'CREATE_ALBUM_RESPONSE';

export const EDIT_ALBUM_REQUEST = 'EDIT_ALBUM_REQUEST';
export const EDIT_ALBUM_RESPONSE = 'EDIT_ALBUM_RESPONSE';

export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_RESPONSE = 'DELETE_ALBUM_RESPONSE';

// *---*---* Photos *---*---*

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_RESPONSE = 'GET_PHOTOS_RESPONSE';

export const CREATE_PHOTO_REQUEST = 'CREATE_PHOTO_REQUEST';
export const CREATE_PHOTO_RESPONSE = 'CREATE_PHOTO_RESPONSE';

export const EDIT_PHOTO_REQUEST = 'EDIT_PHOTO_REQUEST';
export const EDIT_PHOTO_RESPONSE = 'EDIT_PHOTO_RESPONSE';

export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO_REQUEST';
export const DELETE_PHOTO_RESPONSE = 'DELETE_PHOTO_RESPONSE';